### ISSUE TITLE
Now that tox has docs please restart this

### ISSUE THREAD

**Issue by optimumtact** [mahkoh/Xot#9]
Thank you very much

http://toktok.github.io/spec.html

**Comment by optimumtact** [comment]
Please do the needful

**Comment by installgen4** [comment]
RAPE ME DADDY

**Comment by installgen4** [comment]
:eggplant:

**Comment by mahkoh** [comment]
Docs are actually looking pretty good now.

**Comment by suhr** [comment]
There's https://github.com/tox-rs/tox now though.
